<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.http.client.configuration' shared service.

return $this->services['ps_checkout.http.client.configuration'] = new \PrestaShop\Module\PrestashopCheckout\Http\CheckoutHttpClientConfigurationBuilder(($this->services['ps_checkout.environment.payment'] ?? ($this->services['ps_checkout.environment.payment'] = new \PrestaShop\Module\PrestashopCheckout\Environment\PaymentEnv())), ($this->services['ps_checkout.prestashop.router'] ?? ($this->services['ps_checkout.prestashop.router'] = new \PrestaShop\Module\PrestashopCheckout\Routing\Router())), ($this->services['ps_checkout.context.shop'] ?? ($this->services['ps_checkout.context.shop'] = new \PrestaShop\Module\PrestashopCheckout\ShopContext())), ($this->services['ps_checkout.repository.prestashop.account'] ?? $this->load('getPsCheckout_Repository_Prestashop_AccountService.php')), ($this->services['ps_checkout.context.prestashop'] ?? ($this->services['ps_checkout.context.prestashop'] = new \PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext())), ($this->services['ps_checkout.logger.configuration'] ?? $this->load('getPsCheckout_Logger_ConfigurationService.php')), ($this->services['ps_checkout.logger'] ?? $this->load('getPsCheckout_LoggerService.php')));
