<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.command.handler.order.add_order_payment' shared service.

return $this->services['ps_checkout.command.handler.order.add_order_payment'] = new \PrestaShop\Module\PrestashopCheckout\Order\CommandHandler\AddOrderPaymentCommandHandler(($this->services['ps_checkout.event.dispatcher'] ?? $this->load('getPsCheckout_Event_DispatcherService.php')), ($this->services['ps_checkout.funding_source.translation'] ?? $this->load('getPsCheckout_FundingSource_TranslationService.php')), ($this->services['ps_checkout.paypal.configuration'] ?? $this->load('getPsCheckout_Paypal_ConfigurationService.php')));
