<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.order.state.service.order_state_mapper' shared service.

return $this->services['ps_checkout.order.state.service.order_state_mapper'] = new \PrestaShop\Module\PrestashopCheckout\Order\State\Service\OrderStateMapper(($this->services['ps_checkout.configuration'] ?? $this->load('getPsCheckout_ConfigurationService.php')));
