<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.event.dispatcher.factory' shared service.

return $this->services['ps_checkout.event.dispatcher.factory'] = new \PrestaShop\Module\PrestashopCheckout\Event\SymfonyEventDispatcherFactory(($this->services['ps_checkout.logger'] ?? $this->load('getPsCheckout_LoggerService.php')), ($this->services['ps_checkout.logger.configuration'] ?? $this->load('getPsCheckout_Logger_ConfigurationService.php')));
