<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrcXmag\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrcXmag/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNrcXmag.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNrcXmag\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNrcXmag\appAppKernelProdContainer([
    'container.build_hash' => 'NrcXmag',
    'container.build_id' => '0c0f6b0a',
    'container.build_time' => 1715569716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrcXmag');
