<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.command.handler.order.create_order' shared service.

return $this->services['ps_checkout.command.handler.order.create_order'] = new \PrestaShop\Module\PrestashopCheckout\Order\CommandHandler\CreateOrderCommandHandler(($this->services['ps_checkout.context.state.manager'] ?? ($this->services['ps_checkout.context.state.manager'] = new \PrestaShop\Module\PrestashopCheckout\Context\ContextStateManager())), ($this->services['ps_checkout.event.dispatcher'] ?? $this->load('getPsCheckout_Event_DispatcherService.php')), ($this->services['ps_checkout.repository.pscheckoutcart'] ?? $this->load('getPsCheckout_Repository_PscheckoutcartService.php')), ($this->services['ps_checkout.order.state.service.order_state_mapper'] ?? $this->load('getPsCheckout_Order_State_Service_OrderStateMapperService.php')), ($this->services['ps_checkout.module'] ?? $this->load('getPsCheckout_ModuleService.php')), ($this->services['ps_checkout.order.service.check_order_amount'] ?? ($this->services['ps_checkout.order.service.check_order_amount'] = new \PrestaShop\Module\PrestashopCheckout\Order\Service\CheckOrderAmount())));
