<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.command.handler.paypal.order.create_paypal_order' shared service.

return $this->services['ps_checkout.command.handler.paypal.order.create_paypal_order'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\Order\CommandHandler\CreatePayPalOrderCommandHandler(($this->services['ps_checkout.http.client.checkout'] ?? $this->load('getPsCheckout_Http_Client_CheckoutService.php')), ($this->services['ps_checkout.event.dispatcher'] ?? $this->load('getPsCheckout_Event_DispatcherService.php')), ($this->services['ps_checkout.context.shop'] ?? ($this->services['ps_checkout.context.shop'] = new \PrestaShop\Module\PrestashopCheckout\ShopContext())));
