<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.repository.prestashop.account' shared service.

return $this->services['ps_checkout.repository.prestashop.account'] = new \PrestaShop\Module\PrestashopCheckout\Repository\PsAccountRepository(($this->services['ps_checkout.configuration'] ?? $this->load('getPsCheckout_ConfigurationService.php')), ($this->services['ps_accounts.facade'] ?? $this->load('getPsAccounts_FacadeService.php')));
