<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ODjwC8XEHkZV6hWYZRD'."\n".'JaCMLjn+HlV1azNEBdCXsklSCagzSpc/RE1nPHxaw3+vB914t9DTW3NmYiaxZolg'."\n".'2/lPl2Gnwb1NzZMtCiF/ibv5xBu2HsNwqeISIEbsagsx/IzguVx6swIwiqkY0H27'."\n".'OaxqMO2aYQ76+f+yJLjQoimzEKaHvKIYsq2qS9LLa41dARG2aCWFj+AzGhIFAghy'."\n".'1aMqAjyK+GoQhifT7oaMyO4BzMXT5nFHrWj1TsiApFUzyX4q/hiekOD+1upsRBvS'."\n".'gP6O/svyRAc5bwfgwHelK/7wR2t2MVGbDwbqu6nsqqgjvRFWd3bfaoH5t1v1Fdn6'."\n".'7wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
