<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQyXWusF\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQyXWusF/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQyXWusF.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQyXWusF\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerQyXWusF\appAppKernelDevDebugContainer([
    'container.build_hash' => 'QyXWusF',
    'container.build_id' => '51445357',
    'container.build_time' => 1715579902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQyXWusF');
